# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lge/phoenix-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter phoenix_sprout q910,$(TARGET_DEVICE)),)

endif
